"""Writes ic_launcher_foreground.xml (Android adaptive-icon foreground) from geometry.py."""
from geometry import paths, fitted

FG = "#FF6B4A"
# 108dp canvas; the launcher mask keeps a 66dp circle, so the mark spans ~56dp.
body, bars = paths(fitted(108, 56))

open("ic_launcher_foreground.xml", "w").write(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- RomRunner mark: a flying game cartridge. Generated by branding/android_icon.py; edit the source, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{FG}"
        android:fillType="evenOdd"
        android:pathData="{body}" />
    <path
        android:fillColor="{FG}"
        android:pathData="{bars}" />
</vector>
''')
# Same geometry as SVG with the 66dp safe zone drawn, for eyeballing.
open("android-check.svg", "w").write(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="432">
<rect width="108" height="108" fill="#0E0A22"/><circle cx="54" cy="54" r="33" fill="none" stroke="#3DF2FF" stroke-width=".4" stroke-dasharray="1 1"/>
<path fill="{FG}" fill-rule="evenodd" d="{body}"/><path fill="{FG}" d="{bars}"/></svg>''')
