"""Bake the RomRunner mark into Android vector-drawable paths.
VectorDrawable has no skew or masks, so the skew is applied to every point (arcs become
cubic Beziers, which stay exact under affine transforms) and cutouts use evenOdd fill."""
import math

TAN = math.tan(math.radians(-10))
S, CX, CY = 0.14, 223, 256            # mark units -> 108dp adaptive canvas, centred

def T(x, y):
    x, y = x + TAN * y + 50, y          # translate(50 0) skewX(-10)
    return (54 + (x - CX) * S, 54 + (y - CY) * S)

def fmt(p): return f"{p[0]:.2f},{p[1]:.2f}"

def arc(c, r, a0, a1):
    """Cubic segments for a circular arc (angles in degrees, |sweep| <= 90)."""
    a0, a1 = math.radians(a0), math.radians(a1)
    k = 4 / 3 * math.tan((a1 - a0) / 4)
    p0 = (c[0] + r * math.cos(a0), c[1] + r * math.sin(a0))
    p3 = (c[0] + r * math.cos(a1), c[1] + r * math.sin(a1))
    p1 = (p0[0] - k * r * math.sin(a0), p0[1] + k * r * math.cos(a0))
    p2 = (p3[0] + k * r * math.sin(a1), p3[1] - k * r * math.cos(a1))
    return p0, f"C{fmt(T(*p1))} {fmt(T(*p2))} {fmt(T(*p3))}"

def rrect(x, y, w, h, r):
    corners = [((x + w - r, y + r), -90, 0), ((x + w - r, y + h - r), 0, 90),
               ((x + r, y + h - r), 90, 180), ((x + r, y + r), 180, 270)]
    d = ""
    for c, a0, a1 in corners:
        p0, seg = arc(c, r, a0, a1)
        d += ("M" if not d else "L") + fmt(T(*p0)) + seg
    return d + "Z"

def card():
    x0, y0, x1, y1, r, ch = 190, 96, 390, 416, 24, 50
    d = f"M{fmt(T(x0 + r, y0))}L{fmt(T(x1 - ch, y0))}L{fmt(T(x1, y0 + ch))}L{fmt(T(x1, y1 - r))}"
    for c, a0, a1, nxt in [((x1 - r, y1 - r), 0, 90, (x0 + r, y1)), ((x0 + r, y1 - r), 90, 180, (x0, y0 + r)),
                           ((x0 + r, y0 + r), 180, 270, None)]:
        d += arc(c, r, a0, a1)[1]
        if nxt: d += "L" + fmt(T(*nxt))
    return d + "Z"

def rounded_triangle(pts, r):
    """Triangle grown by r with round joins (matches stroke-linejoin=round, width 2r)."""
    n, d = len(pts), ""
    for i in range(n):
        prev, cur, nxt = pts[i - 1], pts[i], pts[(i + 1) % n]
        cx, cy = sum(p[0] for p in pts) / n, sum(p[1] for p in pts) / n
        def normal(a, b):  # edge normal pointing away from the centroid
            dx, dy = b[0] - a[0], b[1] - a[1]
            nx, ny = dy, -dx
            if nx * ((a[0] + b[0]) / 2 - cx) + ny * ((a[1] + b[1]) / 2 - cy) < 0: nx, ny = -nx, -ny
            return math.degrees(math.atan2(ny, nx))
        a0, a1 = normal(prev, cur), normal(cur, nxt)
        sweep = (a1 - a0 + 180) % 360 - 180   # short way round
        a1 = a0 + sweep
        steps = max(1, math.ceil((a1 - a0) / 90))
        for s in range(steps):
            b0, b1 = a0 + (a1 - a0) * s / steps, a0 + (a1 - a0) * (s + 1) / steps
            p0, seg = arc(cur, r, b0, b1)
            d += ("M" if not d else "L") + fmt(T(*p0)) + seg if s == 0 else seg
    return d + "Z"

body = card() + "".join(rrect(x, 124, 16, 44, 6) for x in (222, 252, 282, 312)) \
       + rounded_triangle([(262, 246), (340, 296), (262, 346)], 9)
bars = rrect(70, 214, 92, 26, 13) + rrect(112, 283, 50, 26, 13) + rrect(44, 352, 118, 26, 13)

FG = "#FF6B4A"
open("ic_launcher_foreground.xml", "w").write(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- RomRunner mark: a flying SD card. Generated by branding/android_icon.py; edit the source, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{FG}"
        android:fillType="evenOdd"
        android:pathData="{body}" />
    <path
        android:fillColor="{FG}"
        android:pathData="{bars}" />
</vector>
''')
# Same geometry as SVG, for visual checking against the safe zone.
open("android-check.svg", "w").write(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="432">
<rect width="108" height="108" fill="#0E0A22"/><circle cx="54" cy="54" r="33" fill="none" stroke="#3DF2FF" stroke-width=".4" stroke-dasharray="1 1"/>
<path fill="{FG}" fill-rule="evenodd" d="{body}"/><path fill="{FG}" d="{bars}"/></svg>''')
